# Generated by Django 5.1.2 on 2024-11-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
